### ISSUE TITLE
creating Disks fails with uninitialized constant Azure::Core

### ISSUE THREAD

**Issue by phanindrakalva** [fog/fog-azure-rm#307]
I'm unable to create the disks in azure. Below are the steps I did to create but it is failing.

Versions:
fog-azure-rm (0.3.2)
ruby version 2.4.0

```
azure_storage_service = Fog::Storage::AzureRM.new(
  :tenant_id => '<Tenantid>',                                                      
  :client_id =>    '<Clientid>',                                                   
  :client_secret => '<ClientSecret>',                                              
  :subscription_id => '<Subscriptionid>'
)
```
```

 azure_storage_service.create_disk('disk_name',1023)
/usr/local/lib/ruby/gems/2.4.0/gems/fog-azure-rm-0.3.2/lib/fog/azurerm/requests/storage/create_page_blob.rb:13:in `rescue in create_page_blob': uninitialized constant Azure::Core (NameError)
    from /usr/local/lib/ruby/gems/2.4.0/gems/fog-azure-rm-0.3.2/lib/fog/azurerm/requests/storage/create_page_blob.rb:11:in `create_page_blob'
    from /usr/local/lib/ruby/gems/2.4.0/gems/fog-azure-rm-0.3.2/lib/fog/azurerm/requests/storage/create_disk.rb:37:in `create_disk'
    from createDisk.rb:12:in `<main>'
```

**Comment by bilal-naeem-confiz** [comment]
Hi @phanindrakalva 
Make sure you have all the gems installed. I executed the integration test for `data_disk` and it ran smoothly. Can you share your script which you are using to create the data disk?

**Comment by phanindrakalva** [comment]
@bilal-naeem-confiz, Below is the script I used 

```

require 'fog/azurerm'

azure_storage_service = Fog::Storage.new(
  :provider => 'AzureRM',
  :tenant_id => '15ccb6d1-d335-4996-b6f9-7b6925f08121',                                                                                   # Tenant id of Azure Active Directory Application
  :client_id =>    'b128aea8-a4d8-41de-83ef-629722f1b36a',                                                                                # Client id of Azure Active Directory Application
  :client_secret => 'ZIF+Nb30F9JZgVEaB/Evjs/t9h4vpNfIyKI158QLmFk=',                                                                       # Client Secret of Azure Active Directory Application
  :subscription_id => '7cffd821-ea47-4b66-a39b-a18b447720a1'
)

azure_storage_service.create_disk('disk_name',1023)
azure_storage_service.directories.get('<Container Name>', max_keys: 1)
```


```
/Users/phanindrakalva/.rvm/gems/ruby-2.3.1/gems/fog-azure-rm-0.3.2/lib/fog/azurerm/requests/storage/create_page_blob.rb:13:in `rescue in create_page_blob': uninitialized constant Azure::Core (NameError)
	from /Users/phanindrakalva/.rvm/gems/ruby-2.3.1/gems/fog-azure-rm-0.3.2/lib/fog/azurerm/requests/storage/create_page_blob.rb:11:in `create_page_blob'
	from /Users/phanindrakalva/.rvm/gems/ruby-2.3.1/gems/fog-azure-rm-0.3.2/lib/fog/azurerm/requests/storage/create_disk.rb:37:in `create_disk'
	from rog.rb:11:in `<main>'
```

**Comment by bilal-naeem-confiz** [comment]
@phanindrakalva if you don'e mention the container name in the `create_disk` method, it would try to create the disk in the default container `vhds`. Can you verify if there is a container named `vhds` in your storage account. If there isn't, then you would have to create the container first and create the disk after that.

**Comment by phanindrakalva** [comment]
@bilal-naeem-confiz I'm using `azure_storage_service` to create the disks and they are failing. I tried with container as well and it failed

`azure_storage_service.create_disk('disk_name',1023, :container_name => 'test')
`
```
/Users/phanindrakalva/.rvm/gems/ruby-2.3.1/gems/fog-azure-rm-0.3.2/lib/fog/azurerm/requests/storage/create_page_blob.rb:13:in `rescue in create_page_blob': uninitialized constant Azure::Core (NameError)
	from /Users/phanindrakalva/.rvm/gems/ruby-2.3.1/gems/fog-azure-rm-0.3.2/lib/fog/azurerm/requests/storage/create_page_blob.rb:11:in `create_page_blob'
	from /Users/phanindrakalva/.rvm/gems/ruby-2.3.1/gems/fog-azure-rm-0.3.2/lib/fog/azurerm/requests/storage/create_disk.rb:37:in `create_disk'
	from rog.rb:11:in `<main>'
```

**Comment by bilal-naeem-confiz** [comment]
@phanindrakalva have you given storage account name and storage account key to `azure_storage_service` that you created?

**Comment by phanindrakalva** [comment]
@bilal-naeem-confiz You are awesome!!!  It worked

I was creating the wrong object. I'm creating the object with tenant_id, client_id and secret keys but I need to create it using storage account and storage keys. Thank you so much.

**Comment by bilal-naeem-confiz** [comment]
@phanindrakalva happy to help
