### ISSUE TITLE
The integration test of container.rb failed

### ISSUE THREAD

**Issue by bingosummer** [fog/fog-azure-rm#357]
```
~/fog-azure-rm/test/integration$ DEBUG=true ruby container.rb
[fog][DEBUG] Creating Resource Group: Blob-RG-15128311478565743.
[fog][DEBUG] Resource Group Blob-RG-15128311478565743 created successfully.
[fog][DEBUG] Creating Storage Account: sa15128311502476647 in Resource Group Blob-RG-15128311478565743.
[fog][DEBUG] Storage Account created successfully.
[fog][DEBUG] Getting storage access keys for storage account: sa15128311502476647, {:request_id=>"066fe810-db0d-4c5c-b569-6d80388102d1"}.
[fog][DEBUG] Storage access keys for storage account: sa15128311502476647 listed successfully.
[fog][DEBUG] Checking container con15128311478565743.
[fog][DEBUG] Getting container properties: con15128311478565743, options: {:request_id=>"1400ca85-5ca7-4fa1-ba01-ab9e13290b65"}.
--REQUEST-BEGIN---------------------------
method:
get
uri:
https://sa15128311502476647.blob.core.windows.net/con15128311478565743?restype=container
headers:
{"User-Agent"=>"Azure-Storage/0.11.5-preview (Ruby 2.4.2-p198; Linux linux-gnu)", "x-ms-date"=>"Sat, 09 Dec 2017 14:53:13 GMT", "x-ms-version"=>"2015-04-05", "DataServiceVersion"=>"1.0;NetFx", "MaxDataServiceVersion"=>"3.0;NetFx", "Content-Type"=>"application/atom+xml; charset=utf-8", "x-ms-client-request-id"=>"1400ca85-5ca7-4fa1-ba01-ab9e13290b65", "Content-Length"=>"0", "Authorization"=>"SharedKey sa15128311502476647:y9mC7HXenwxTCQXgzYlYMEeazMC/sl3Eow2gnn/kOXc="}
body:

--REQUEST-END---------------------------
--RESPONSE-BEGIN---------------------------
status_code:
404
headers:
{"content-length"=>"225", "content-type"=>"application/xml", "server"=>"Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0", "x-ms-request-id"=>"309b8bab-001e-003e-6afd-70c93a000000", "x-ms-version"=>"2015-04-05", "date"=>"Sat, 09 Dec 2017 14:53:13 GMT", "connection"=>"close"}
body:
<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.
RequestId:309b8bab-001e-003e-6afd-70c93a000000
Time:2017-12-09T14:53:13.7370854Z</Message></Error>
--RESPONSE-END---------------------------
/home/binxi/.gem/ruby/2.4.2/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/document.rb:44: warning: constant ::Fixnum is deprecated
[fog][DEBUG] The specified container con15128311478565743 does not exist.
Container doesn't exist.
[fog][DEBUG] Creating container: con15128311478565743. options: {:public_access_level=>nil, :request_id=>"1f41d09a-bdfd-484d-b416-ad6abbfdf7db"}
--REQUEST-BEGIN---------------------------
method:
put
uri:
https://sa15128311502476647.blob.core.windows.net/con15128311478565743?restype=container
headers:
{"User-Agent"=>"Azure-Storage/0.11.5-preview (Ruby 2.4.2-p198; Linux linux-gnu)", "x-ms-date"=>"Sat, 09 Dec 2017 14:53:13 GMT", "x-ms-version"=>"2015-04-05", "DataServiceVersion"=>"1.0;NetFx", "MaxDataServiceVersion"=>"3.0;NetFx", "Content-Type"=>"application/atom+xml; charset=utf-8", "x-ms-client-request-id"=>"1f41d09a-bdfd-484d-b416-ad6abbfdf7db", "Content-Length"=>"0", "Authorization"=>"SharedKey sa15128311502476647:TVQ5E3W3KV8d2zRyMjNVSlw6mMpFNdzm4+36HNDWDqw="}
body:

--REQUEST-END---------------------------
--RESPONSE-BEGIN---------------------------
status_code:
201
headers:
{"transfer-encoding"=>"chunked", "last-modified"=>"Sat, 09 Dec 2017 14:53:13 GMT", "etag"=>"\"0x8D53F1492D82543\"", "server"=>"Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0", "x-ms-request-id"=>"123ae39f-001e-016e-65fd-709067000000", "x-ms-version"=>"2015-04-05", "date"=>"Sat, 09 Dec 2017 14:53:12 GMT", "connection"=>"close"}
body:

--RESPONSE-END---------------------------
[fog][DEBUG] ["/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/http/retry_policy.rb:52:in `call'", "/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/http/http_request.rb:110:in `block in with_filter'", "/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/http/signer_filter.rb:28:in `call'", "/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/http/signer_filter.rb:28:in `call'", "/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/http/http_request.rb:110:in `block in with_filter'", "/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/service.rb:36:in `call'", "/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/filtered_service.rb:34:in `call'", "/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/signed_service.rb:41:in `call'", "/home/binxi/.gem/ruby/2.4.2/gems/azure-storage-0.11.5.preview/lib/azure/storage/service/storage_service.rb:53:in `call'", "/home/binxi/.gem/ruby/2.4.2/gems/azure-storage-0.11.5.preview/lib/azure/storage/blob/blob_service.rb:59:in `call'", "/home/binxi/.gem/ruby/2.4.2/gems/azure-storage-0.11.5.preview/lib/azure/storage/blob/container.rb:108:in `get_container_properties'", "/home/binxi/.gem/ruby/2.4.2/gems/fog-azure-rm-0.3.9/lib/fog/azurerm/requests/storage/get_container_properties.rb:12:in `get_container_properties'", "/home/binxi/.gem/ruby/2.4.2/gems/fog-azure-rm-0.3.9/lib/fog/azurerm/requests/storage/check_container_exists.rb:10:in `check_container_exists'", "/home/binxi/.gem/ruby/2.4.2/gems/fog-azure-rm-0.3.9/lib/fog/azurerm/models/storage/directories.rb:70:in `check_container_exists'", "container.rb:67:in `<main>'"]
Integration Test for container is failing: #<RuntimeError: #<Azure::Core::Http::HTTPError:47030152860960 @http_response: #<Azure::Core::Http::HttpResponse:0x0000558c1f1c32b0 @http_response=#<Faraday::Response:0x0000558c1f1c3350 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:get @body="\xEF\xBB\xBF<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.\nRequestId:309b8bab-001e-003e-6afd-70c93a000000\nTime:2017-12-09T14:53:13.7370854Z</Message></Error>" @url=#<URI::HTTPS https://sa15128311502476647.blob.core.windows.net/con15128311478565743?restype=container> @request=#<Faraday::RequestOptions open_timeout=60> @request_headers={"User-Agent"=>"Azure-Storage/0.11.5-preview (Ruby 2.4.2-p198; Linux linux-gnu)", "x-ms-date"=>"Sat, 09 Dec 2017 14:53:13 GMT", "x-ms-version"=>"2015-04-05", "DataServiceVersion"=>"1.0;NetFx", "MaxDataServiceVersion"=>"3.0;NetFx", "Content-Type"=>"application/atom+xml; charset=utf-8", "x-ms-client-request-id"=>"1400ca85-5ca7-4fa1-ba01-ab9e13290b65", "Content-Length"=>"0", "Authorization"=>"SharedKey sa15128311502476647:y9mC7HXenwxTCQXgzYlYMEeazMC/sl3Eow2gnn/kOXc="} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x0000558c1f1c3350 ...> @response_headers={"content-length"=>"225", "content-type"=>"application/xml", "server"=>"Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0", "x-ms-request-id"=>"309b8bab-001e-003e-6afd-70c93a000000", "x-ms-version"=>"2015-04-05", "date"=>"Sat, 09 Dec 2017 14:53:13 GMT", "connection"=>"close"} @status=404 @reason_phrase="The specified container does not exist.">>, @uri=#<URI::HTTPS https://sa15128311502476647.blob.core.windows.net/con15128311478565743?restype=container>>, @uri: #<URI::HTTPS https://sa15128311502476647.blob.core.windows.net/con15128311478565743?restype=container>, @status_code: 404, @type: "ContainerNotFound", @description: "The specified container does not exist.\nRequestId:309b8bab-001e-003e-6afd-70c93a000000\nTime:2017-12-09T14:53:13.7370854Z">
/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/http/retry_policy.rb:52:in `call'
/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/http/http_request.rb:110:in `block in with_filter'
/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/http/signer_filter.rb:28:in `call'
/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/http/signer_filter.rb:28:in `call'
/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/http/http_request.rb:110:in `block in with_filter'
/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/service.rb:36:in `call'
/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/filtered_service.rb:34:in `call'
/home/binxi/.gem/ruby/2.4.2/gems/azure-core-0.1.13/lib/azure/core/signed_service.rb:41:in `call'
/home/binxi/.gem/ruby/2.4.2/gems/azure-storage-0.11.5.preview/lib/azure/storage/service/storage_service.rb:53:in `call'
/home/binxi/.gem/ruby/2.4.2/gems/azure-storage-0.11.5.preview/lib/azure/storage/blob/blob_service.rb:59:in `call'
/home/binxi/.gem/ruby/2.4.2/gems/azure-storage-0.11.5.preview/lib/azure/storage/blob/container.rb:108:in `get_container_properties'
/home/binxi/.gem/ruby/2.4.2/gems/fog-azure-rm-0.3.9/lib/fog/azurerm/requests/storage/get_container_properties.rb:12:in `get_container_properties'
/home/binxi/.gem/ruby/2.4.2/gems/fog-azure-rm-0.3.9/lib/fog/azurerm/requests/storage/check_container_exists.rb:10:in `check_container_exists'
/home/binxi/.gem/ruby/2.4.2/gems/fog-azure-rm-0.3.9/lib/fog/azurerm/models/storage/directories.rb:70:in `check_container_exists'
container.rb:67:in `<main>'>
/home/binxi/.gem/ruby/2.4.2/gems/fog-azure-rm-0.3.9/lib/fog/azurerm/utilities/general.rb:62:in `raise_azure_exception'
/home/binxi/.gem/ruby/2.4.2/gems/fog-azure-rm-0.3.9/lib/fog/azurerm/requests/storage/create_container.rb:14:in `rescue in create_container'
/home/binxi/.gem/ruby/2.4.2/gems/fog-azure-rm-0.3.9/lib/fog/azurerm/requests/storage/create_container.rb:11:in `create_container'
/home/binxi/.gem/ruby/2.4.2/gems/fog-azure-rm-0.3.9/lib/fog/azurerm/models/storage/directory.rb:125:in `save'
/home/binxi/.gem/ruby/2.4.2/gems/fog-core-1.45.0/lib/fog/core/collection.rb:50:in `create'
container.rb:74:in `<main>'
[fog][DEBUG] Deleting Resource Group: Blob-RG-15128311478565743.
[fog][DEBUG] Resource Group Blob-RG-15128311478565743 deleted successfully.
```

After I remove the lines in `container.rb`, the test is succeeded. Could you please have a look?

```
  flag = storage_data.directories.check_container_exists(container_name)
  puts "Container doesn't exist." unless flag
```

**Comment by bingosummer** [comment]
@azeem-sajid-confiz Could you please have a look?

**Comment by iamAzeem** [comment]
@bingosummer 
Which lines you removed? The existence test at the end?
Following two lines?
```
flag = storage_data.directories.check_container_exists(container_name)
puts "Container doesn't exist." unless flag
```

@maham-nazir-confiz 
Kindly take a look at this issue.

**Comment by bingosummer** [comment]
@iamAzeem yes. The existence test.
I found that the test `container.rb` would fail with these two lines, from my side.
Not sure whether it is reproducible from your side.

**Comment by maham-nazir-confiz** [comment]
@bingosummer 
Hi, this error happens because of a fault in the latest `azure-core` gem (version 0.1.13). We have requested them to fix this issue.
This is the link of the PR in which this issue has been fixed.
Link => https://github.com/Azure/azure-ruby-asm-core/pull/52
Feel free to use this PR to build the `azure-core` gem or you can downgrade to version 0.1.12. The error doesn't occur in that version.
